### ISSUE TITLE
Add release tags and advertise OpenUPM support

### ISSUE THREAD

**Issue by randomPoison** [zchfvy/GizmosPlus#1]
Would it be possible to add a tag (optionally setup via a GitHub release) for the latest version of GizmosPlus? I ask because this package is [listed on OpenUPM](https://openupm.com/packages/com.zchfvy.gizmosplus/) but currently cannot be downloaded because there are no tagged releases. The tag just needs to be a valid semver string, so something like `v0.1.4` to match the current package version should work.

Also, if you're interested in better supporting accessing the package via OpenUPM, you can add instructions for doing so to your README. For projects that aren't already using Git as version control system, pulling in the package as a Git dependency can be inconvenient since it means all team members need to install Git on their development machines in order to load the project. Making the package available via OpenUPM ensures that the project can still be opened without needing Git as a dependency.

Also, thanks a ton for putting together this package! I've found it to be very useful and appreciate the contribution to the UPM ecosystem :heart:

**Comment by zchfvy** [comment]
Hey,

Thanks for leaving this issue; I hadn't even heard about OpenUPM until your brought it to my attention just now. 

Changes have been made and the OpenUPM listing seems to not have errors in it now!
